### ISSUE TITLE
Грешка приликом покретања апликације

### ISSUE THREAD

**Issue by sivancev** [zenariworks/crkva#13]
Пратим readme фајл и све прође, до последњег корака, када избаци ову грешку доле.

git commit 8a15bc200d7f6d7637b5e09435b9abc39f5f325e (HEAD -> main, origin/main, origin/HEAD)

sasa  betelgeuse  ~/projects/crkva  main  $  
docker compose up
[+] Running 2/0
 ✔ Container crkva-db-1   Running                                                                                                                                                                                                0.0s 
 ✔ Container crkva-app-1  Created                                                                                                                                                                                                0.0s 
Attaching to crkva-app-1, crkva-db-1
crkva-app-1  | Waiting for database...
crkva-app-1  | Database available!
crkva-app-1  | Operations to perform:
crkva-app-1  |   Apply all migrations: admin, auth, contenttypes, registar, sessions
crkva-app-1  | Running migrations:
crkva-app-1  |   No migrations to apply.
crkva-app-1  | Traceback (most recent call last):
crkva-app-1  |   File "/app/manage.py", line 23, in <module>
crkva-app-1  |     main()
crkva-app-1  |   File "/app/manage.py", line 19, in main
crkva-app-1  |     execute_from_command_line(sys.argv)
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
crkva-app-1  |     utility.execute()
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
crkva-app-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
crkva-app-1  |     self.execute(*args, **cmd_options)
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
crkva-app-1  |     output = self.handle(*args, **options)
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
crkva-app-1  |     collected = self.collect()
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
crkva-app-1  |     handler(path, prefixed_path, storage)
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 378, in copy_file
crkva-app-1  |     self.storage.save(prefixed_path, source_file)
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/core/files/storage/base.py", line 38, in save
crkva-app-1  |     name = self._save(name, content)
crkva-app-1  |   File "/py/lib/python3.9/site-packages/django/core/files/storage/filesystem.py", line 87, in _save
crkva-app-1  |     os.makedirs(directory, exist_ok=True)
crkva-app-1  |   File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
crkva-app-1  |     makedirs(head, exist_ok=exist_ok)
crkva-app-1  |   File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
crkva-app-1  |     makedirs(head, exist_ok=exist_ok)
crkva-app-1  |   File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
crkva-app-1  |     mkdir(name, mode)
crkva-app-1  | PermissionError: [Errno 13] Permission denied: '/vol/web/static'
crkva-app-1 exited with code 1

**Comment by zenfiric** [comment]
Мислим да је тешко да репродукујемо, а пројекат је већ прилично стабилан. Затворићу, ако затреба, отварамо поново.
